-- ══════════════════════════════════════════════════════════════════
-- Ikatu — Planilha de Relação de Projetos e Metadados 2026
-- Execute este script no Supabase SQL Editor para criar as tabelas,
-- habilitar RLS e realizar a carga inicial dos dados.
-- ══════════════════════════════════════════════════════════════════

-- 1. TABELA DE LOJAS E FABRICANTES
CREATE TABLE IF NOT EXISTS public.metadata_lojas (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  franquia    TEXT NOT NULL CHECK (franquia IN ('iGUi', 'Conceito', 'Internacional', 'Splash')),
  loja        TEXT NOT NULL,
  fabrica     TEXT NOT NULL,
  created_at  TIMESTAMPTZ DEFAULT now(),
  updated_at  TIMESTAMPTZ DEFAULT now(),
  CONSTRAINT unique_franquia_loja UNIQUE (franquia, loja)
);

-- 2. TABELA DE MODELOS DE PISCINAS
CREATE TABLE IF NOT EXISTS public.metadata_piscinas (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  marca       TEXT NOT NULL CHECK (marca IN ('iGUi', 'Splash')),
  modelo      TEXT NOT NULL,
  created_at  TIMESTAMPTZ DEFAULT now(),
  updated_at  TIMESTAMPTZ DEFAULT now(),
  CONSTRAINT unique_marca_modelo UNIQUE (marca, modelo)
);

-- 3. TABELA DE RELAÇÃO DE PROJETOS 2026
CREATE TABLE IF NOT EXISTS public.project_relations (
  id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  loja           TEXT NOT NULL,
  project_code   TEXT,
  data_entrada   DATE,
  data_saida     DATE,
  modelo_01      TEXT,
  modelo_02      TEXT,
  modelo_03      TEXT,
  modelo_04      TEXT,
  modelo_05      TEXT,
  franquia       TEXT NOT NULL,
  fabrica        TEXT,
  projetista     TEXT,
  projetista_id  UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  tipo_projeto   TEXT,
  pago           BOOLEAN NOT NULL DEFAULT false,
  obs            TEXT,
  created_at     TIMESTAMPTZ DEFAULT now(),
  updated_at     TIMESTAMPTZ DEFAULT now()
);

-- Habilitar Row Level Security (RLS) nas três tabelas
ALTER TABLE public.metadata_lojas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.metadata_piscinas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.project_relations ENABLE ROW LEVEL SECURITY;

-- Políticas de segurança: Acesso restrito a administradores
DROP POLICY IF EXISTS "metadata_lojas_admin_all" ON public.metadata_lojas;
CREATE POLICY "metadata_lojas_admin_all" ON public.metadata_lojas
  FOR ALL TO authenticated
  USING (public.is_admin())
  WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS "metadata_piscinas_admin_all" ON public.metadata_piscinas;
CREATE POLICY "metadata_piscinas_admin_all" ON public.metadata_piscinas
  FOR ALL TO authenticated
  USING (public.is_admin())
  WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS "project_relations_admin_all" ON public.project_relations;
CREATE POLICY "project_relations_admin_all" ON public.project_relations
  FOR ALL TO authenticated
  USING (public.is_admin())
  WITH CHECK (public.is_admin());


-- 4. CARGA INICIAL: LOJAS E FABRICANTES (SEED DATA)
INSERT INTO public.metadata_lojas (franquia, loja, fabrica) VALUES
-- iGUi (Padrão)
('iGUi', 'Alagoinhas', 'Alagoinhas - BA'),
('iGUi', 'Assis', 'Cedral - SP'),
('iGUi', 'Barreiras', 'Alagoinhas - BA'),
('iGUi', 'Boa Vista', 'Benevides - PA'),
('iGUi', 'Camaçari - Guarajuba', 'Alagoinhas - BA'),
('iGUi', 'Carazinho', 'Santo Antônio da Patrulha - SC'),
('iGUi', 'Conselheiro Lafaiete', 'Esmeraldas - MG'),
('iGUi', 'Florianópolis - Norte', 'São João do Itaperiú - SC'),
('iGUi', 'Francisco Beltrão', 'Engenheiro Beltrão - PR'),
('iGUi', 'Goiânia I - Jardim América', 'Cedral - SP'),
('iGUi', 'Goiânia II', 'Cedral - SP'),
('iGUi', 'Goiânia III', 'Cedral - SP'),
('iGUi', 'Jataí', 'Prata - MG'),
('iGUi', 'Jequié', 'Alagoinhas - BA'),
('iGUi', 'Juazeiro do Norte', 'Pacajus - CE'),
('iGUi', 'Marabá', 'Benevides - PA'),
('iGUi', 'Montenegro', 'Santo Antônio da Patrulha - SC'),
('iGUi', 'Novo Hamburgo', 'Santo Antônio da Patrulha - SC'),
('iGUi', 'Patos de Minas', 'Prata - MG'),
('iGUi', 'Primavera do Leste', 'Cuiabá - MT'),
('iGUi', 'Rio Verde', 'Cedral - SP'),
('iGUi', 'Santa Maria', 'Santo Antônio da Patrulha - SC'),
('iGUi', 'São José', 'São João do Itaperiú - SC'),
('iGUi', 'São Paulo - Gabriel Monteiro', 'Guaratinguetá - SP'),
('iGUi', 'Serrinha', 'Alagoinhas - BA'),
('iGUi', 'Sete Lagoas', 'Esmeraldas - MG'),
('iGUi', 'Sorriso', 'Cuiabá - MT'),

-- iGUi Conceito
('Conceito', 'Anápolis', 'Prata - MG'),
('Conceito', 'Aracaju', 'Alagoinhas - BA'),
('Conceito', 'Araçatuba', 'Cedral - SP'),
('Conceito', 'Balneário Camboriú', 'São João do Itaperiú - SC'),
('Conceito', 'Barreiras', 'Alagoinhas - BA'),
('Conceito', 'Barueri (Alphaville)', 'Guaratinguetá - SP'),
('Conceito', 'Belém', 'Benevides - PA'),
('Conceito', 'Belo Horizonte', 'Esmeraldas - MG'),
('Conceito', 'Betim', 'Esmeraldas - MG'),
('Conceito', 'Boa Vista', 'Benevides - PA'),
('Conceito', 'Brasília', 'Prata - MG'),
('Conceito', 'Campinas', 'Analândia - SP'),
('Conceito', 'Campinas (Dom Pedro)', 'Analândia - SP'),
('Conceito', 'Campos dos Goytacazes', 'Campos dos Goytacazes - RJ'),
('Conceito', 'Canoas', 'Santo Antônio da Patrulha - SC'),
('Conceito', 'Cascavel', 'Engenheiro Beltrão - PR'),
('Conceito', 'Cianorte', 'Engenheiro Beltrão - PR'),
('Conceito', 'Cuiabá', 'Cuiabá - MT'),
('Conceito', 'Curitiba', 'São João do Itaperiú - SC'),
('Conceito', 'Dourados', 'Engenheiro Beltrão - PR'),
('Conceito', 'Feira de Santana', 'Alagoinhas - BA'),
('Conceito', 'Florianópolis (Casa & Design)', 'São João do Itaperiú - SC'),
('Conceito', 'Fortaleza', 'Pacajus - CE'),
('Conceito', 'Guarapuava', 'Engenheiro Beltrão - PR'),
('Conceito', 'Ipatinga', 'Esmeraldas - MG'),
('Conceito', 'João Pessoa', 'Vitória de Santo Antão - PE'),
('Conceito', 'Juiz de Fora', 'Esmeraldas - MG'),
('Conceito', 'Londrina', 'Engenheiro Beltrão - PR'),
('Conceito', 'Maceió', 'Vitória de Santo Antão - PE'),
('Conceito', 'Natal', 'Pacajus - CE'),
('Conceito', 'Niterói', 'Itaboraí - RJ'),
('Conceito', 'Parnaíba', 'Pacajus - CE'),
('Conceito', 'Passo Fundo', 'Santo Antônio da Patrulha - SC'),
('Conceito', 'Pelotas', 'Santo Antônio da Patrulha - SC'),
('Conceito', 'Petrópolis/Itaipava', 'Campos dos Goytacazes - RJ'),
('Conceito', 'Piracicaba', 'Guaratinguetá - SP'),
('Conceito', 'Porto Alegre', 'Santo Antônio da Patrulha - SC'),
('Conceito', 'Porto Alegre (Zona Sul)', 'Santo Antônio da Patrulha - SC'),
('Conceito', 'Porto Velho', 'Cuiabá - MT'),
('Conceito', 'Praia do Forte', 'Alagoinhas - BA'),
('Conceito', 'Presidente Prudente', 'Cedral - SP'),
('Conceito', 'Recife I', 'Vitória de Santo Antão - PE'),
('Conceito', 'Recife II (Porfirio)', 'Vitória de Santo Antão - PE'),
('Conceito', 'Resende', 'Guaratinguetá - SP'),
('Conceito', 'Ribeirão Preto', 'Analândia - SP'),
('Conceito', 'Rio de Janeiro (Barra)', 'Itaboraí - RJ'),
('Conceito', 'Rio de Janeiro (São Conrado)', 'Itaboraí - RJ'),
('Conceito', 'Santa Maria', 'Santo Antônio da Patrulha - SC'),
('Conceito', 'São José', 'São João do Itaperiú - SC'),
('Conceito', 'São José do Rio Preto', 'Cedral - SP'),
('Conceito', 'São José dos Campos', 'Guaratinguetá - SP'),
('Conceito', 'São Paulo (Alameda Gabriel Monteiro)', 'Guaratinguetá - SP'),
('Conceito', 'São Paulo (Av. dos Bandeirantes)', 'Guaratinguetá - SP'),
('Conceito', 'Sorocaba', 'Analândia - SP'),
('Conceito', 'Taubaté', 'Guaratinguetá - SP'),
('Conceito', 'Teixeira de Freitas', 'Alagoinhas - BA'),
('Conceito', 'Teresina', 'Pacajus - CE'),
('Conceito', 'Toledo', 'Engenheiro Beltrão - PR'),
('Conceito', 'Uberaba', 'Prata - MG'),
('Conceito', 'Uberlândia', 'Prata - MG'),
('Conceito', 'Valinhos', 'Analândia - SP'),
('Conceito', 'Varzedo', 'Alagoinhas - BA'),
('Conceito', 'Vila Velha', 'Campos dos Goytacazes - RJ'),
('Conceito', 'Vitória da Conquista', 'Alagoinhas - BA'),
('Conceito', 'Votuporanga', 'Cedral - SP'),
('Conceito', 'Xangri-Lá', 'Santo Antônio da Patrulha - SC'),

-- iGUi Internacional
('Internacional', 'USA', 'Campos do Goytacazes - RJ'),
('Internacional', 'Florida', 'Campos do Goytacazes - RJ'),
('Internacional', 'Ricoom', 'Campos do Goytacazes - RJ'),
('Internacional', 'Ocala USA', 'Campos do Goytacazes - RJ'),
('Internacional', 'Amaral US', 'Campos do Goytacazes - RJ'),
('Internacional', 'Victor Moreno US', 'Campos do Goytacazes - RJ'),
('Internacional', 'B. Martin Gonzalez', 'Campos do Goytacazes - RJ'),
('Internacional', 'Michele Alves US', 'Campos do Goytacazes - RJ'),
('Internacional', 'Cjconsorte', 'Campos do Goytacazes - RJ'),
('Internacional', 'iGUi Sarasota', 'Campos do Goytacazes - RJ'),
('Internacional', 'Portugal', 'Campos do Goytacazes - RJ'),
('Internacional', 'Uruguay', 'Campos do Goytacazes - RJ'),
('Internacional', 'Guyana', 'Campos do Goytacazes - RJ'),
('Internacional', 'Panamá', 'Campos do Goytacazes - RJ'),
('Internacional', 'Colombia', 'Campos do Goytacazes - RJ'),
('Internacional', 'Nova Zelandia', 'Campos do Goytacazes - RJ'),
('Internacional', 'Holanda', 'Campos do Goytacazes - RJ'),
('Internacional', 'Suriname', 'Campos do Goytacazes - RJ'),
('Internacional', 'Asunción - Paraguay', 'Engenheiro Beltão - PR'),
('Internacional', 'Limpio - Paraguay', 'Engenheiro Beltão - PR'),
('Internacional', 'Luque Samber - Paraguay', 'Engenheiro Beltão - PR'),
('Internacional', 'Paraná Entre Rios', 'Argentina - AR'),
('Internacional', 'Santa Fé Argentina', 'Argentina - AR'),
('Internacional', 'Bahía Blanca', 'Argentina - AR'),
('Internacional', 'Tucuman', 'Argentina - AR'),
('Internacional', 'Salta', 'Argentina - AR'),
('Internacional', 'La Plata', 'Argentina - AR'),

-- Splash (Lojas)
('Splash', 'Alagoinhas', 'Alagoinhas - BA'),
('Splash', 'Aracaju', 'Alagoinhas - BA'),
('Splash', 'Barra', 'Alagoinhas - BA'),
('Splash', 'Barra Dos Coqueiros', 'Alagoinhas - BA'),
('Splash', 'Barreiras', 'Alagoinhas - BA'),
('Splash', 'Camaçari', 'Alagoinhas - BA'),
('Splash', 'Entre Rios', 'Alagoinhas - BA'),
('Splash', 'Estância', 'Alagoinhas - BA'),
('Splash', 'Eunapolis', 'Alagoinhas - BA'),
('Splash', 'Feira De Santana', 'Alagoinhas - BA'),
('Splash', 'Guanambi', 'Alagoinhas - BA'),
('Splash', 'Ilheus', 'Alagoinhas - BA'),
('Splash', 'Irecê', 'Alagoinhas - BA'),
('Splash', 'Itabaiana', 'Alagoinhas - BA'),
('Splash', 'Itaberaba', 'Alagoinhas - BA'),
('Splash', 'Itabuna', 'Alagoinhas - BA'),
('Splash', 'Jacobina', 'Alagoinhas - BA'),
('Splash', 'Jequie', 'Alagoinhas - BA'),
('Splash', 'Juazeiro', 'Alagoinhas - BA'),
('Splash', 'Lagarto', 'Alagoinhas - BA'),
('Splash', 'Lauro De Freitas', 'Alagoinhas - BA'),
('Splash', 'Luis Eduardo Magalhaes', 'Alagoinhas - BA'),
('Splash', 'Nossa Senhora Da Glória', 'Alagoinhas - BA'),
('Splash', 'Paulo Afonso', 'Alagoinhas - BA'),
('Splash', 'Petrolina', 'Alagoinhas - BA'),
('Splash', 'Porto Seguro', 'Alagoinhas - BA'),
('Splash', 'Salvador', 'Alagoinhas - BA'),
('Splash', 'Santo Antonio De Jesus', 'Alagoinhas - BA'),
('Splash', 'Seabra', 'Alagoinhas - BA'),
('Splash', 'Senhor Do Bonfim', 'Alagoinhas - BA'),
('Splash', 'Serrinha', 'Alagoinhas - BA'),
('Splash', 'Simões Filho', 'Alagoinhas - BA'),
('Splash', 'Teixeira De Freitas', 'Alagoinhas - BA'),
('Splash', 'Valença', 'Alagoinhas - BA'),
('Splash', 'Vera Cruz', 'Alagoinhas - BA'),
('Splash', 'Vitória Da Conquista', 'Alagoinhas - BA'),
('Splash', 'Araraquara', 'Analandia - SP'),
('Splash', 'Araras', 'Analandia - SP'),
('Splash', 'Artur Nogueira', 'Analandia - SP'),
('Splash', 'Bauru', 'Analandia - SP'),
('Splash', 'Brodowski', 'Analandia - SP'),
('Splash', 'Campinas', 'Analandia - SP'),
('Splash', 'Franca', 'Analandia - SP'),
('Splash', 'Guaxupé', 'Analandia - SP'),
('Splash', 'Ibitinga', 'Analandia - SP'),
('Splash', 'Igarapava', 'Analandia - SP'),
('Splash', 'Jaboticabal', 'Analandia - SP'),
('Splash', 'Jaguariuna', 'Analandia - SP'),
('Splash', 'Jau', 'Analandia - SP'),
('Splash', 'Lençois Paulista', 'Analandia - SP'),
('Splash', 'Limeira', 'Analandia - SP'),
('Splash', 'Matão', 'Analandia - SP'),
('Splash', 'Mococa', 'Analandia - SP'),
('Splash', 'Mogi Mirim', 'Analandia - SP'),
('Splash', 'Nova Odessa', 'Analandia - SP'),
('Splash', 'Paulinia', 'Analandia - SP'),
('Splash', 'Pirassununga', 'Analandia - SP'),
('Splash', 'Ribeirão Preto', 'Analandia - SP'),
('Splash', 'Rio Claro', 'Analandia - SP'),
('Splash', 'São Carlos', 'Analandia - SP'),
('Splash', 'São Joaquim Da Barra', 'Analandia - SP'),
('Splash', 'São Sebastião Do Paraíso', 'Analandia - SP'),
('Splash', 'Sertãozinho', 'Analandia - SP'),
('Splash', 'Sumaré', 'Analandia - SP'),
('Splash', 'Tambaú', 'Analandia - SP'),
('Splash', 'Vinhedo', 'Analandia - SP'),
('Splash', 'Abaetetuba', 'Benevides - PA'),
('Splash', 'Altamira', 'Benevides - PA'),
('Splash', 'Ananindeua', 'Benevides - PA'),
('Splash', 'Araguaina', 'Benevides - PA'),
('Splash', 'Bacabal', 'Benevides - PA'),
('Splash', 'Barreirinhas', 'Benevides - PA'),
('Splash', 'Belem', 'Benevides - PA'),
('Splash', 'Benevides', 'Benevides - PA'),
('Splash', 'Boa Vista', 'Benevides - PA'),
('Splash', 'Bragança', 'Benevides - PA'),
('Splash', 'Castanhal', 'Benevides - PA'),
('Splash', 'Dom Eliseu', 'Benevides - PA'),
('Splash', 'Imperatriz', 'Benevides - PA'),
('Splash', 'Iranduba', 'Benevides - PA'),
('Splash', 'Itaituba', 'Benevides - PA'),
('Splash', 'Macapá', 'Benevides - PA'),
('Splash', 'Manaus', 'Benevides - PA'),
('Splash', 'Marabá', 'Benevides - PA'),
('Splash', 'Marituba', 'Benevides - PA'),
('Splash', 'Paragominas', 'Benevides - PA'),
('Splash', 'Parauapebas', 'Benevides - PA'),
('Splash', 'Salinópolis', 'Benevides - PA'),
('Splash', 'Santa Ines', 'Benevides - PA'),
('Splash', 'Santarem', 'Benevides - PA'),
('Splash', 'São José De Ribamar', 'Benevides - PA'),
('Splash', 'Sao Luis', 'Benevides - PA'),
('Splash', 'Tucurui', 'Benevides - PA'),
('Splash', 'Xinguara', 'Benevides - PA'),
('Splash', 'Aracruz', 'Campos Dos Goytacazes - RJ'),
('Splash', 'Cachoeiro Do Itapemirim', 'Campos Dos Goytacazes - RJ'),
('Splash', 'Campos Dos Goytacases', 'Campos Dos Goytacazes - RJ'),
('Splash', 'Campos Dos Goytacazes', 'Campos Dos Goytacazes - RJ'),
('Splash', 'Cariacica', 'Campos Dos Goytacazes - RJ'),
('Splash', 'Castelo', 'Campos Dos Goytacazes - RJ'),
('Splash', 'Colatina', 'Campos Dos Goytacazes - RJ'),
('Splash', 'Guaçuí', 'Campos Dos Goytacazes - RJ'),
('Splash', 'Guarapari', 'Campos Dos Goytacazes - RJ'),
('Splash', 'Itaperuna', 'Campos Dos Goytacazes - RJ'),
('Splash', 'Linhares', 'Campos Dos Goytacazes - RJ'),
('Splash', 'Marataízes', 'Campos Dos Goytacazes - RJ'),
('Splash', 'São Gabriel Da Palha', 'Campos Dos Goytacazes - RJ'),
('Splash', 'Sao Mateus', 'Campos Dos Goytacazes - RJ'),
('Splash', 'Serra', 'Campos Dos Goytacazes - RJ'),
('Splash', 'Vila Velha', 'Campos Dos Goytacazes - RJ'),
('Splash', 'Adamantina', 'Cedral - SP'),
('Splash', 'Anastácio', 'Cedral - SP'),
('Splash', 'Andradina', 'Cedral - SP'),
('Splash', 'Aracatuba', 'Cedral - SP'),
('Splash', 'Assis', 'Cedral - SP'),
('Splash', 'Bady Bassitt', 'Cedral - SP'),
('Splash', 'Barretos', 'Cedral - SP'),
('Splash', 'Bebedouro', 'Cedral - SP'),
('Splash', 'Birigui', 'Cedral - SP'),
('Splash', 'Buritama', 'Cedral - SP'),
('Splash', 'Campo Grande', 'Cedral - SP'),
('Splash', 'Cassilândia', 'Cedral - SP'),
('Splash', 'Catanduva Sp', 'Cedral - SP'),
('Splash', 'Chapadão Do Sul', 'Cedral - SP'),
('Splash', 'Corumba', 'Cedral - SP'),
('Splash', 'Dracena', 'Cedral - SP'),
('Splash', 'Guaíra', 'Cedral - SP'),
('Splash', 'Jales', 'Cedral - SP'),
('Splash', 'Lins', 'Cedral - SP'),
('Splash', 'Maracaju', 'Cedral - SP'),
('Splash', 'Marilia', 'Cedral - SP'),
('Splash', 'Miguelópolis', 'Cedral - SP'),
('Splash', 'Novo Horizonte', 'Cedral - SP'),
('Splash', 'Olimpia', 'Cedral - SP'),
('Splash', 'Ourinhos', 'Cedral - SP'),
('Splash', 'Paulicéia', 'Cedral - SP'),
('Splash', 'Penapolis', 'Cedral - SP'),
('Splash', 'Pereira Barreto', 'Cedral - SP'),
('Splash', 'Presidente Epitácio', 'Cedral - SP'),
('Splash', 'Santa Fé Do Sul', 'Cedral - SP'),
('Splash', 'São José Do Rio Preto', 'Cedral - SP'),
('Splash', 'Tanabi', 'Cedral - SP'),
('Splash', 'Três Lagoas', 'Cedral - SP'),
('Splash', 'Tupã', 'Cedral - SP'),
('Splash', 'Votuporanga', 'Cedral - SP'),
('Splash', 'Água Boa', 'Cuiabá - MT'),
('Splash', 'Alta Floresta', 'Cuiabá - MT'),
('Splash', 'Ariquemes', 'Cuiabá - MT'),
('Splash', 'Barra Do Garças', 'Cuiabá - MT'),
('Splash', 'Caceres', 'Cuiabá - MT'),
('Splash', 'Cacoal', 'Cuiabá - MT'),
('Splash', 'Campo Novo Do Parecis', 'Cuiabá - MT'),
('Splash', 'Campo Verde', 'Cuiabá - MT'),
('Splash', 'Confresa', 'Cuiabá - MT'),
('Splash', 'Cuiaba', 'Cuiabá - MT'),
('Splash', 'Jaciara', 'Cuiabá - MT'),
('Splash', 'Ji-Parana', 'Cuiabá - MT'),
('Splash', 'Juína', 'Cuiabá - MT'),
('Splash', 'Lucas Do Rio Verde', 'Cuiabá - MT'),
('Splash', 'Nova Mutum', 'Cuiabá - MT'),
('Splash', 'Peixoto De Azevedo', 'Cuiabá - MT'),
('Splash', 'Porto Velho', 'Cuiabá - MT'),
('Splash', 'Primavera Do Leste', 'Cuiabá - MT'),
('Splash', 'Rio Branco', 'Cuiabá - MT'),
('Splash', 'Rondonópolis', 'Cuiabá - MT'),
('Splash', 'Sinop', 'Cuiabá - MT'),
('Splash', 'Sorriso', 'Cuiabá - MT'),
('Splash', 'Tangará Da Serra', 'Cuiabá - MT'),
('Splash', 'Varzea Grande', 'Cuiabá - MT'),
('Splash', 'Vilhena', 'Cuiabá - MT'),
('Splash', 'Águas De São Pedro', 'Elias Fausto - SP'),
('Splash', 'Aluminio', 'Elias Fausto - SP'),
('Splash', 'Americana', 'Elias Fausto - SP'),
('Splash', 'Amparo', 'Elias Fausto - SP'),
('Splash', 'Araçoiaba Da Serra', 'Elias Fausto - SP'),
('Splash', 'Atibaia', 'Elias Fausto - SP'),
('Splash', 'Avaré', 'Elias Fausto - SP'),
('Splash', 'Barueri', 'Elias Fausto - SP'),
('Splash', 'Boituva', 'Elias Fausto - SP'),
('Splash', 'Botucatu', 'Elias Fausto - SP'),
('Splash', 'Bragança Paulista', 'Elias Fausto - SP'),
('Splash', 'Caieiras', 'Elias Fausto - SP'),
('Splash', 'Cajamar', 'Elias Fausto - SP'),
('Splash', 'Capivari', 'Elias Fausto - SP'),
('Splash', 'Cerquilho', 'Elias Fausto - SP'),
('Splash', 'Indaiatuba', 'Elias Fausto - SP'),
('Splash', 'Itapetininga', 'Elias Fausto - SP'),
('Splash', 'Itapeva', 'Elias Fausto - SP'),
('Splash', 'Itu', 'Elias Fausto - SP'),
('Splash', 'Jundiaí', 'Elias Fausto - SP'),
('Splash', 'Pilar Do Sul', 'Elias Fausto - SP'),
('Splash', 'Piracicaba', 'Elias Fausto - SP'),
('Splash', 'Registro', 'Elias Fausto - SP'),
('Splash', 'Santa Bárbara D''Oeste', 'Elias Fausto - SP'),
('Splash', 'Sao Paulo', 'Elias Fausto - SP'),
('Splash', 'São Roque', 'Elias Fausto - SP'),
('Splash', 'Socorro', 'Elias Fausto - SP'),
('Splash', 'Sorocaba', 'Elias Fausto - SP'),
('Splash', 'Taquarituba', 'Elias Fausto - SP'),
('Splash', 'Tatuí', 'Elias Fausto - SP'),
('Splash', 'Vargem Grande Paulista', 'Elias Fausto - SP'),
('Splash', 'Apucarana', 'Engenheiro Beltrão - PR'),
('Splash', 'Arapongas', 'Engenheiro Beltrão - PR'),
('Splash', 'Assis Chateaubriand', 'Engenheiro Beltrão - PR'),
('Splash', 'Caçador', 'Engenheiro Beltrão - PR'),
('Splash', 'Cambé', 'Engenheiro Beltrão - PR'),
('Splash', 'Campo Mourão', 'Engenheiro Beltrão - PR'),
('Splash', 'Canoinhas', 'Engenheiro Beltrão - PR'),
('Splash', 'Cascavel', 'Engenheiro Beltrão - PR'),
('Splash', 'Chapeco', 'Engenheiro Beltrão - PR'),
('Splash', 'Cianorte', 'Engenheiro Beltrão - PR'),
('Splash', 'Colorado', 'Engenheiro Beltrão - PR'),
('Splash', 'Cornélio Procópio', 'Engenheiro Beltrão - PR'),
('Splash', 'Dois Vizinhos', 'Engenheiro Beltrão - PR'),
('Splash', 'Dourados', 'Engenheiro Beltrão - PR'),
('Splash', 'Engenheiro Beltrão', 'Engenheiro Beltrão - PR'),
('Splash', 'Foz Do Iguaçu', 'Engenheiro Beltrão - PR'),
('Splash', 'Francisco Beltrão', 'Engenheiro Beltrão - PR'),
('Splash', 'Guarapuava', 'Engenheiro Beltrão - PR'),
('Splash', 'Irati', 'Engenheiro Beltrão - PR'),
('Splash', 'Ivaiporã', 'Engenheiro Beltrão - PR'),
('Splash', 'Laranjeiras Do Sul', 'Engenheiro Beltrão - PR'),
('Splash', 'Loanda', 'Engenheiro Beltrão - PR'),
('Splash', 'Londrina', 'Engenheiro Beltrão - PR'),
('Splash', 'Marechal Cândido Rondon', 'Engenheiro Beltrão - PR'),
('Splash', 'Marialva', 'Engenheiro Beltrão - PR'),
('Splash', 'Maringa', 'Engenheiro Beltrão - PR'),
('Splash', 'Medianeira', 'Engenheiro Beltrão - PR'),
('Splash', 'Naviraí', 'Engenheiro Beltrão - PR'),
('Splash', 'Nova Andradina', 'Engenheiro Beltrão - PR'),
('Splash', 'Paranavaí', 'Engenheiro Beltrão - PR'),
('Splash', 'Pato Branco', 'Engenheiro Beltrão - PR'),
('Splash', 'Porto União', 'Engenheiro Beltrão - PR'),
('Splash', 'Santo Antônio Da Platina', 'Engenheiro Beltrão - PR'),
('Splash', 'São Miguel Do Oeste', 'Engenheiro Beltrão - PR'),
('Splash', 'Siqueira Campos', 'Engenheiro Beltrão - PR'),
('Splash', 'Telemaco Borba', 'Engenheiro Beltrão - PR'),
('Splash', 'Toledo', 'Engenheiro Beltrão - PR'),
('Splash', 'Umuarama', 'Engenheiro Beltrão - PR'),
('Splash', 'Xanxerê', 'Engenheiro Beltrão - PR'),
('Splash', 'Barbacena', 'Esmeraldas - MG'),
('Splash', 'Belo Horizonte', 'Esmeraldas - MG'),
('Splash', 'Betim', 'Esmeraldas - MG'),
('Splash', 'Bom Despacho', 'Esmeraldas - MG'),
('Splash', 'Cataguases', 'Esmeraldas - MG'),
('Splash', 'Conselheiro Lafaiete', 'Esmeraldas - MG'),
('Splash', 'Contagem', 'Esmeraldas - MG'),
('Splash', 'Curvelo', 'Esmeraldas - MG'),
('Splash', 'Divinopolis', 'Esmeraldas - MG'),
('Splash', 'Extrema', 'Esmeraldas - MG'),
('Splash', 'Formiga', 'Esmeraldas - MG'),
('Splash', 'Governador Valadares', 'Esmeraldas - MG'),
('Splash', 'Guapé', 'Esmeraldas - MG'),
('Splash', 'Igarape', 'Esmeraldas - MG'),
('Splash', 'Ipatinga', 'Esmeraldas - MG'),
('Splash', 'Itabira', 'Esmeraldas - MG'),
('Splash', 'Itajuba', 'Esmeraldas - MG'),
('Splash', 'Itaobim', 'Esmeraldas - MG'),
('Splash', 'João Monlevade', 'Esmeraldas - MG'),
('Splash', 'Juiz De Fora', 'Esmeraldas - MG'),
('Splash', 'Lagoa Santa', 'Esmeraldas - MG'),
('Splash', 'Lavras', 'Esmeraldas - MG'),
('Splash', 'Manhuaçu', 'Esmeraldas - MG'),
('Splash', 'Montes Claros', 'Esmeraldas - MG'),
('Splash', 'Muriae', 'Esmeraldas - MG'),
('Splash', 'Nova Serrana', 'Esmeraldas - MG'),
('Splash', 'Passos', 'Esmeraldas - MG'),
('Splash', 'Poços De Caldas', 'Esmeraldas - MG'),
('Splash', 'Ribeirão Das Neves', 'Esmeraldas - MG'),
('Splash', 'São Lourenço', 'Esmeraldas - MG'),
('Splash', 'Sete Lagoas', 'Esmeraldas - MG'),
('Splash', 'Teofilo Otoni', 'Esmeraldas - MG'),
('Splash', 'Ubá', 'Esmeraldas - MG'),
('Splash', 'Varginha', 'Esmeraldas - MG'),
('Splash', 'Viçosa', 'Esmeraldas - MG'),
('Splash', 'Arujá', 'Guaratinguetá - SP'),
('Splash', 'Bertioga', 'Guaratinguetá - SP'),
('Splash', 'Caçapava', 'Guaratinguetá - SP'),
('Splash', 'Caraguatatuba', 'Guaratinguetá - SP'),
('Splash', 'Cruzeiro', 'Guaratinguetá - SP'),
('Splash', 'Guaratinguetá', 'Guaratinguetá - SP'),
('Splash', 'Guarujá', 'Guaratinguetá - SP'),
('Splash', 'Itanhaém', 'Guaratinguetá - SP'),
('Splash', 'Itaquaquecetuba', 'Guaratinguetá - SP'),
('Splash', 'Jacarei', 'Guaratinguetá - SP'),
('Splash', 'Lorena', 'Guaratinguetá - SP'),
('Splash', 'Maua', 'Guaratinguetá - SP'),
('Splash', 'Mogi Das Cruzes', 'Guaratinguetá - SP'),
('Splash', 'Mongaguá', 'Guaratinguetá - SP'),
('Splash', 'Peruibe', 'Guaratinguetá - SP'),
('Splash', 'Pindamonhangaba', 'Guaratinguetá - SP'),
('Splash', 'Praia Grande', 'Guaratinguetá - SP'),
('Splash', 'Resende', 'Guaratinguetá - SP'),
('Splash', 'São Bernardo Do Campo', 'Guaratinguetá - SP'),
('Splash', 'São Jose Dos Campos', 'Guaratinguetá - SP'),
('Splash', 'São Paulo', 'Guaratinguetá - SP'),
('Splash', 'São Sebastião', 'Guaratinguetá - SP'),
('Splash', 'Suzano', 'Guaratinguetá - SP'),
('Splash', 'Taubaté', 'Guaratinguetá - SP'),
('Splash', 'Ubatuba', 'Guaratinguetá - SP'),
('Splash', 'Volta Redonda', 'Guaratinguetá - SP'),
('Splash', 'Angra Dos Reis', 'Itaboraí - RJ'),
('Splash', 'Araruama', 'Itaboraí - RJ'),
('Splash', 'Belford Roxo', 'Itaboraí - RJ'),
('Splash', 'Guapimirim', 'Itaboraí - RJ'),
('Splash', 'Itaborai', 'Itaboraí - RJ'),
('Splash', 'Itaguai', 'Itaboraí - RJ'),
('Splash', 'Macae', 'Itaboraí - RJ'),
('Splash', 'Magé', 'Itaboraí - RJ'),
('Splash', 'Marica', 'Itaboraí - RJ'),
('Splash', 'Miguel Pereira', 'Itaboraí - RJ'),
('Splash', 'Niteroi', 'Itaboraí - RJ'),
('Splash', 'Nova Friburgo', 'Itaboraí - RJ'),
('Splash', 'Petropolis', 'Itaboraí - RJ'),
('Splash', 'Rio Bonito', 'Itaboraí - RJ'),
('Splash', 'Rio Das Ostras', 'Itaboraí - RJ'),
('Splash', 'Rio De Janeiro', 'Itaboraí - RJ'),
('Splash', 'São Gonçalo', 'Itaboraí - RJ'),
('Splash', 'São Pedro Da Aldeia', 'Itaboraí - RJ'),
('Splash', 'Saquarema', 'Itaboraí - RJ'),
('Splash', 'Tres Rios', 'Itaboraí - RJ'),
('Splash', 'Acaraú', 'Pacajus - CE'),
('Splash', 'Açu', 'Pacajus - CE'),
('Splash', 'Aquiraz', 'Pacajus - CE'),
('Splash', 'Aracati', 'Pacajus - CE'),
('Splash', 'Barbalha', 'Pacajus - CE'),
('Splash', 'Caicó', 'Pacajus - CE'),
('Splash', 'Camocim', 'Pacajus - CE'),
('Splash', 'Campo Maior', 'Pacajus - CE'),
('Splash', 'Canindé', 'Pacajus - CE'),
('Splash', 'Caucaia', 'Pacajus - CE'),
('Splash', 'Caxias', 'Pacajus - CE'),
('Splash', 'Chapadinha', 'Pacajus - CE'),
('Splash', 'Crateus', 'Pacajus - CE'),
('Splash', 'Crato', 'Pacajus - CE'),
('Splash', 'Floriano', 'Pacajus - CE'),
('Splash', 'Fortaleza', 'Pacajus - CE'),
('Splash', 'Goianinha', 'Pacajus - CE'),
('Splash', 'Iguatu', 'Pacajus - CE'),
('Splash', 'Itapipoca', 'Pacajus - CE'),
('Splash', 'Jaguaribe', 'Pacajus - CE'),
('Splash', 'Juazeiro Do Norte', 'Pacajus - CE'),
('Splash', 'Maracanau', 'Pacajus - CE'),
('Splash', 'Mossoró', 'Pacajus - CE'),
('Splash', 'Natal', 'Pacajus - CE'),
('Splash', 'Pacajus', 'Pacajus - CE'),
('Splash', 'Parnaiba', 'Pacajus - CE'),
('Splash', 'Parnamirim', 'Pacajus - CE'),
('Splash', 'Pau Dos Ferros', 'Pacajus - CE'),
('Splash', 'Picos', 'Pacajus - CE'),
('Splash', 'Quixada', 'Pacajus - CE'),
('Splash', 'Russas', 'Pacajus - CE'),
('Splash', 'São Gonçalo Do Amarante', 'Pacajus - CE'),
('Splash', 'Sobral', 'Pacajus - CE'),
('Splash', 'Teresina', 'Pacajus - CE'),
('Splash', 'Tianguá', 'Pacajus - CE'),
('Splash', 'Timon', 'Pacajus - CE'),
('Splash', 'Araquari', 'São João do Itaperiú - SC (Parati)'),
('Splash', 'Ararangua', 'São João do Itaperiú - SC (Parati)'),
('Splash', 'Araucaria', 'São João do Itaperiú - SC (Parati)'),
('Splash', 'Balneario Camboriu', 'São João do Itaperiú - SC (Parati)'),
('Splash', 'Barra Velha', 'São João do Itaperiú - SC (Parati)'),
('Splash', 'Biguaçu', 'São João do Itaperiú - SC (Parati)'),
('Splash', 'Blumenau', 'São João do Itaperiú - SC (Parati)'),
('Splash', 'Brusque', 'São João do Itaperiú - SC (Parati)'),
('Splash', 'Concordia', 'São João do Itaperiú - SC (Parati)'),
('Splash', 'Criciuma', 'São João do Itaperiú - SC (Parati)'),
('Splash', 'Curitiba', 'São João do Itaperiú - SC (Parati)'),
('Splash', 'Florianopolis', 'São João do Itaperiú - SC (Parati)'),
('Splash', 'Garuva', 'São João do Itaperiú - SC (Parati)'),
('Splash', 'Governador Celso Ramos', 'São João do Itaperiú - SC (Parati)'),
('Splash', 'Guaramirim', 'São João do Itaperiú - SC (Parati)'),
('Splash', 'Guaratuba', 'São João do Itaperiú - SC (Parati)'),
('Splash', 'Imbituba', 'São João do Itaperiú - SC (Parati)'),
('Splash', 'Indaial', 'São João do Itaperiú - SC (Parati)'),
('Splash', 'Itajai', 'São João do Itaperiú - SC (Parati)'),
('Splash', 'Jaguariaíva', 'São João do Itaperiú - SC (Parati)'),
('Splash', 'Joinville', 'São João do Itaperiú - SC (Parati)'),
('Splash', 'Lages', 'São João do Itaperiú - SC (Parati)'),
('Splash', 'Mafra', 'São João do Itaperiú - SC (Parati)'),
('Splash', 'Paranaguá', 'São João do Itaperiú - SC (Parati)'),
('Splash', 'Penha', 'São João do Itaperiú - SC (Parati)'),
('Splash', 'Ponta Grossa', 'São João do Itaperiú - SC (Parati)'),
('Splash', 'Pontal Do Paraná', 'São João do Itaperiú - SC (Parati)'),
('Splash', 'Porto Belo', 'São João do Itaperiú - SC (Parati)'),
('Splash', 'Rio Do Sul', 'São João do Itaperiú - SC (Parati)'),
('Splash', 'Santo Amaro Da Imperatriz', 'São João do Itaperiú - SC (Parati)'),
('Splash', 'São Jogé', 'São João do Itaperiú - SC (Parati)'),
('Splash', 'Sao Jose Dos Pinhais', 'São João do Itaperiú - SC (Parati)'),
('Splash', 'Sombrio', 'São João do Itaperiú - SC (Parati)'),
('Splash', 'Tijucas', 'São João do Itaperiú - SC (Parati)'),
('Splash', 'Tubarão', 'São João do Itaperiú - SC (Parati)'),
('Splash', 'Alexania', 'Prata - MG'),
('Splash', 'Anapolis', 'Prata - MG'),
('Splash', 'Aparecida De Goiania', 'Prata - MG'),
('Splash', 'Araguari', 'Prata - MG'),
('Splash', 'Araxa', 'Prata - MG'),
('Splash', 'Brasilia', 'Prata - MG'),
('Splash', 'Caldas Novas', 'Prata - MG'),
('Splash', 'Catalao', 'Prata - MG'),
('Splash', 'Cristalina', 'Prata - MG'),
('Splash', 'Formosa', 'Prata - MG'),
('Splash', 'Frutal', 'Prata - MG'),
('Splash', 'Goiania', 'Prata - MG'),
('Splash', 'Gurupi', 'Prata - MG'),
('Splash', 'Ituiutaba', 'Prata - MG'),
('Splash', 'Itumbiara', 'Prata - MG'),
('Splash', 'Jaraguá', 'Prata - MG'),
('Splash', 'Jatai', 'Prata - MG'),
('Splash', 'Luziania', 'Prata - MG'),
('Splash', 'Morrinhos', 'Prata - MG'),
('Splash', 'Palmas', 'Prata - MG'),
('Splash', 'Patos De Minas', 'Prata - MG'),
('Splash', 'Patrocinio', 'Prata - MG'),
('Splash', 'Prata', 'Prata - MG'),
('Splash', 'Quirinópolis', 'Prata - MG'),
('Splash', 'Rio Verde', 'Prata - MG'),
('Splash', 'Senador Canedo', 'Prata - MG'),
('Splash', 'Trindade', 'Prata - MG'),
('Splash', 'Uberaba', 'Prata - MG'),
('Splash', 'Uberlandia', 'Prata - MG'),
('Splash', 'Valparaiso De Goias', 'Prata - MG'),
('Splash', 'Alegrete', 'Santo Antônio da Patrulha - RS'),
('Splash', 'Bage', 'Santo Antônio da Patrulha - RS'),
('Splash', 'Campo Bom', 'Santo Antônio da Patrulha - RS'),
('Splash', 'Canoas', 'Santo Antônio da Patrulha - RS'),
('Splash', 'Carazinho', 'Santo Antônio da Patrulha - RS'),
('Splash', 'Caxias Do Sul', 'Santo Antônio da Patrulha - RS'),
('Splash', 'Eldorado Do Sul', 'Santo Antônio da Patrulha - RS'),
('Splash', 'Erechim', 'Santo Antônio da Patrulha - RS'),
('Splash', 'Frederico Westphalen', 'Santo Antônio da Patrulha - RS'),
('Splash', 'Gravatai', 'Santo Antônio da Patrulha - RS'),
('Splash', 'Ibirubá', 'Santo Antônio da Patrulha - RS'),
('Splash', 'Ijuí', 'Santo Antônio da Patrulha - RS'),
('Splash', 'Jaguarão', 'Santo Antônio da Patrulha - RS'),
('Splash', 'Lajeado', 'Santo Antônio da Patrulha - RS'),
('Splash', 'Montenegro', 'Santo Antônio da Patrulha - RS'),
('Splash', 'Novo Hamburgo', 'Santo Antônio da Patrulha - RS'),
('Splash', 'Osório', 'Santo Antônio da Patrulha - RS'),
('Splash', 'Passo Fundo', 'Santo Antônio da Patrulha - RS'),
('Splash', 'Pelotas', 'Santo Antônio da Patrulha - RS'),
('Splash', 'Porto Alegre', 'Santo Antônio da Patrulha - RS'),
('Splash', 'Presidente Lucena', 'Santo Antônio da Patrulha - RS'),
('Splash', 'Rio Grande', 'Santo Antônio da Patrulha - RS'),
('Splash', 'Santa Cruz Do Sul', 'Santo Antônio da Patrulha - RS'),
('Splash', 'Santa Maria', 'Santo Antônio da Patrulha - RS'),
('Splash', 'Santa Rosa', 'Santo Antônio da Patrulha - RS'),
('Splash', 'Santana Do Livramento', 'Santo Antônio da Patrulha - RS'),
('Splash', 'Santo Angelo', 'Santo Antônio da Patrulha - RS'),
('Splash', 'São Borja', 'Santo Antônio da Patrulha - RS'),
('Splash', 'Sao Gabriel', 'Santo Antônio da Patrulha - RS'),
('Splash', 'São Leopoldo', 'Santo Antônio da Patrulha - RS'),
('Splash', 'São Lourenço Do Sul', 'Santo Antônio da Patrulha - RS'),
('Splash', 'São Sebastião Do Caí', 'Santo Antônio da Patrulha - RS'),
('Splash', 'Taquara', 'Santo Antônio da Patrulha - RS'),
('Splash', 'Viamão', 'Santo Antônio da Patrulha - RS'),
('Splash', 'Xangri-Lá', 'Santo Antônio da Patrulha - RS'),
('Splash', 'Abreu E Lima', 'Vitória de Santo Antão PE'),
('Splash', 'Arapiraca', 'Vitória de Santo Antão PE'),
('Splash', 'Cabedelo', 'Vitória de Santo Antão PE'),
('Splash', 'Cabo De Santo Agostinho', 'Vitória de Santo Antão PE'),
('Splash', 'Cajazeiras', 'Vitória de Santo Antão PE'),
('Splash', 'Camaragibe', 'Vitória de Santo Antão PE'),
('Splash', 'Campina Grande', 'Vitória de Santo Antão PE'),
('Splash', 'Caruaru', 'Vitória de Santo Antão PE'),
('Splash', 'Conde', 'Vitória de Santo Antão PE'),
('Splash', 'Delmiro Gouveia', 'Vitória de Santo Antão PE'),
('Splash', 'Garanhuns', 'Vitória de Santo Antão PE'),
('Splash', 'Gravatá', 'Vitória de Santo Antão PE'),
('Splash', 'Igarassu', 'Vitória de Santo Antão PE'),
('Splash', 'Jaboatao Dos Guararapes', 'Vitória de Santo Antão PE'),
('Splash', 'João Pessoa', 'Vitória de Santo Antão PE'),
('Splash', 'Maceio', 'Vitória de Santo Antão PE'),
('Splash', 'Marechal Deodoro', 'Vitória de Santo Antão PE'),
('Splash', 'Palmares', 'Vitória de Santo Antão PE'),
('Splash', 'Patos', 'Vitória de Santo Antão PE'),
('Splash', 'Penedo', 'Vitória de Santo Antão PE'),
('Splash', 'Petrolândia', 'Vitória de Santo Antão PE'),
('Splash', 'Recife', 'Vitória de Santo Antão PE'),
('Splash', 'Salgueiro', 'Vitória de Santo Antão PE')
ON CONFLICT (franquia, loja) DO UPDATE SET fabrica = EXCLUDED.fabrica;


-- 5. CARGA INICIAL: MODELOS DE PISCINAS (SEED DATA)
INSERT INTO public.metadata_piscinas (marca, modelo) VALUES
-- iGUi (Marca principal e Conceitos)
('iGUi', 'Cetus'),
('iGUi', 'Cetus com Acrílico'),
('iGUi', 'Kéramos'),
('iGUi', 'Kéramos com Acrílico'),
('iGUi', 'Barra'),
('iGUi', 'Faenza'),
('iGUi', 'Faenza com Acrílico'),
('iGUi', 'Arabá'),
('iGUi', 'Arabá com Acrílico'),
('iGUi', 'Murano'),
('iGUi', 'Murano com Acrílico'),
('iGUi', 'Arita'),
('iGUi', 'Arita com Acrílico'),
('iGUi', 'Ática'),
('iGUi', 'Ática com Acrílico'),
('iGUi', 'Aquarium'),
('iGUi', 'Jomon'),
('iGUi', 'Jomon com Acrílico'),
('iGUi', 'Marajoara'),
('iGUi', 'Marajoara com Acrílico'),
('iGUi', 'Aruã'),
('iGUi', 'Aruã com Acrílico'),
('iGUi', 'Vallauris'),
('iGUi', 'Vallauris com Acrílico'),
('iGUi', 'Montelupo'),
('iGUi', 'Montelupo com Acrílico'),
('iGUi', 'Fès Blue'),
('iGUi', 'Fès Blue com Acrílico'),
('iGUi', 'Castelli'),
('iGUi', 'Castelli com Acrílico'),
('iGUi', 'Unlimited'),
('iGUi', 'Mod. 001'),
('iGUi', 'Mod. 002'),
('iGUi', 'Mod. 003'),
('iGUi', 'Mod. 004'),
('iGUi', 'Mod. 005'),
('iGUi', 'Mod. 006'),
('iGUi', 'Mod. 007'),
('iGUi', 'Mod. 008'),
('iGUi', 'Mod. 009'),
('iGUi', 'Mod. 010'),
('iGUi', 'Mod. 011'),
('iGUi', 'Mod. 012'),
('iGUi', 'Mod. 014'),
('iGUi', 'Mod. 015'),
('iGUi', 'Mod. 016'),
('iGUi', 'Mod. 017'),
('iGUi', 'Mod. 018'),
('iGUi', 'Mod. 019'),
('iGUi', 'Mod. 020'),
('iGUi', 'Mod. 021'),
('iGUi', 'Mod. 022'),
('iGUi', 'Mod. 023'),
('iGUi', 'Mod. 024'),
('iGUi', 'Mod. 025'),
('iGUi', 'Mod. 026'),
('iGUi', 'Mod. 027'),
('iGUi', 'Mod. 028'),
('iGUi', 'Mod. 029'),
('iGUi', 'Mod. 030'),
('iGUi', 'Mod. 031'),
('iGUi', 'Mod. 032'),
('iGUi', 'Mod. 033'),
('iGUi', 'Mod. 034'),
('iGUi', 'Mod. 035'),
('iGUi', 'Mod. 036'),
('iGUi', 'Mod. 037'),
('iGUi', 'Mod. 038'),
('iGUi', 'Mod. 039'),
('iGUi', 'Mod. 040'),
('iGUi', 'Mod. 041'),
('iGUi', 'Mod. 042'),
('iGUi', 'Mod. 043'),
('iGUi', 'Mod. 044'),
('iGUi', 'Mod. 045'),
('iGUi', 'Mod. 046'),
('iGUi', 'Mod. 047'),
('iGUi', 'Mod. 052'),
('iGUi', 'Mod. 055'),
('iGUi', 'Mod. 056'),
('iGUi', 'Mod. 059'),
('iGUi', 'Mod. 060'),
('iGUi', 'Mod. 063'),
('iGUi', 'Mod. 064'),
('iGUi', 'Mod. 065'),
('iGUi', 'Mod. 066'),
('iGUi', 'Mod. 067'),
('iGUi', 'Mod. 068'),
('iGUi', 'Mod. 069'),
('iGUi', 'Mod. 070'),
('iGUi', 'Mod. 071'),
('iGUi', 'Mod. 076'),
('iGUi', 'Mod. 081'),
('iGUi', 'Mod. 082'),
('iGUi', 'Mod. 083'),
('iGUi', 'Mod. 084'),
('iGUi', 'Mod. 085'),
('iGUi', 'Mod. 092'),
('iGUi', 'Mod. 093'),
('iGUi', 'C 1'),
('iGUi', 'C 2'),
('iGUi', 'C 3'),
('iGUi', 'C 4'),
('iGUi', 'C 5'),
('iGUi', 'C 6'),
('iGUi', 'C 7'),
('iGUi', 'C 8'),
('iGUi', 'C 9'),
('iGUi', 'C 10'),
('iGUi', 'C 11'),
('iGUi', 'C 12'),
('iGUi', 'C 13'),
('iGUi', 'C 14'),
('iGUi', 'C 15'),
('iGUi', 'C 16'),
('iGUi', 'C 17'),
('iGUi', 'C 18'),
('iGUi', 'C 19'),
('iGUi', 'C 20'),
('iGUi', 'C 21'),
('iGUi', 'C 22'),
('iGUi', 'C 23'),
('iGUi', 'C 24'),
('iGUi', 'C 25'),
('iGUi', 'C 26'),
('iGUi', 'C 27'),
('iGUi', 'C 28'),
('iGUi', 'C 29'),
('iGUi', 'C 30'),
('iGUi', 'C 31'),
('iGUi', 'C 32'),
('iGUi', 'C 33'),
('iGUi', 'C 34'),
('iGUi', 'C 35'),
('iGUi', 'C 36'),

-- Splash (Modelos)
('Splash', 'Atalaia 7m'),
('Splash', 'Atalaia 9m'),
('Splash', 'Bonaire 3m'),
('Splash', 'Bonaire 4m'),
('Splash', 'Bonaire 5m'),
('Splash', 'Bonaire 6m'),
('Splash', 'Bonaire 7m'),
('Splash', 'Bonaire 8m'),
('Splash', 'Cancún 3m'),
('Splash', 'Cancún 4m'),
('Splash', 'Cancún 5m'),
('Splash', 'Cancún 6m'),
('Splash', 'Cancún 7m'),
('Splash', 'Cancún 8m'),
('Splash', 'Cancún 10m'),
('Splash', 'Tortuga 5m'),
('Splash', 'Tortuga 7m'),
('Splash', 'Tortuga 9m'),
('Splash', 'Tortuga 10m'),
('Splash', 'Farol da Barra 4m'),
('Splash', 'Farol da Barra 5m'),
('Splash', 'Farol da Barra 6m'),
('Splash', 'Farol da Barra 7m'),
('Splash', 'Farol da Barra 8m'),
('Splash', 'Farol da Barra 9m'),
('Splash', 'Farol da Barra 10m'),
('Splash', 'Farol da Barra 10m (Especial)'),
('Splash', 'Tropical 3.50m'),
('Splash', 'Tropical 4m (1m)'),
('Splash', 'Tropical 4m'),
('Splash', 'Tropical 5m'),
('Splash', 'Tropical 6m (1.30m)'),
('Splash', 'Tropical 6m'),
('Splash', 'Tropical 7m'),
('Splash', 'Tropical 8m'),
('Splash', 'Tropical 9m'),
('Splash', 'Tropical 10m'),
('Splash', 'Italiana 2.50m'),
('Splash', 'Italiana 3m'),
('Splash', 'Italiana 3.20m'),
('Splash', 'Italiana 3.50m'),
('Splash', 'Italiana 4m'),
('Splash', 'Italiana 5m'),
('Splash', 'Italiana 6m'),
('Splash', 'Italiana 7m'),
('Splash', 'Italiana 8m'),
('Splash', 'Nassau 4m'),
('Splash', 'Tradicional 3.5m'),
('Splash', 'Tradicional 4m (1m)'),
('Splash', 'Tradicional 4m'),
('Splash', 'Tradicional 4.50m'),
('Splash', 'Tradicional 5m (1.2m)'),
('Splash', 'Tradicional 5m'),
('Splash', 'Tradicional 5.50m'),
('Splash', 'Tradicional 6m'),
('Splash', 'Tradicional 6m SPA'),
('Splash', 'Tradicional 6m PRAINHA'),
('Splash', 'Tradicional 6.50m'),
('Splash', 'Tradicional 7m'),
('Splash', 'Tradicional 7m SPA'),
('Splash', 'Tradicional 7m PRAINHA'),
('Splash', 'Tradicional 8m'),
('Splash', 'Tradicional 8m SPA'),
('Splash', 'Tradicional 8m PRAINHA'),
('Splash', 'Tradicional 8.50m'),
('Splash', 'Tradicional 9m'),
('Splash', 'Navagio s/ Ac.'),
('Splash', 'Navagio Ac. Reto 1m'),
('Splash', 'Navagio Ac. L 1m'),
('Splash', 'Navagio Ac. Reto 1.50m'),
('Splash', 'Navagio Ac. L 1.50m')
ON CONFLICT (marca, modelo) DO NOTHING;
